- db/seeds.rb
> Dummy data for item in seed file

- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/index.html.erb
- config/routes.rb
- db/migrate/20170725215009_create_items.rb
- db/schema.rb
- spec/factories/items.rb
- spec/features/visitor_visits_items_index_spec.rb
- spec/models/item_spec.rb
Created Item Model
Created Items Controller
Added Item_Path Route
Created Index show
Created Index.html.erb view
Feature tests pass
> items can be created and viewed from items_path

- app/assets/stylesheets/application.css.scss
- app/views/items/_items.html.erb
- app/views/items/index.html.erb
- app/views/layouts/application.html.erb
- db/seeds.rb
- Added background image to site
- Minor styling tweaks 
- More items in seed file
> Background image

- app/views/carts/index.html.erb
- app/views/items/_items.html.erb
- app/views/items/show.html.erb
Also minor styling changes to similar views
> Cart styling

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/sessions/new.html.erb
- app/views/users/_form.html.erb
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- db/migrate/004_create_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/features/user_can_create_new_account_spec.rb
- spec/features/user_logs_in_to_site_spec.rb
- spec/models/user_spec.rb
All Hail Tom! Iterations completed.
> Iteration 8 and 9 completed

- app/controllers/sessions_controller.rb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/features/user_can_log_out_spec.rb
- spec/features/user_logs_in_to_site_spec.rb
I did this all by my big boy self. Ellen wasn't even here! Please merge this.
> User log out

- app/controllers/orders_controller.rb
- app/models/order.rb
- app/models/user.rb
- app/views/orders/index.html.erb
- config/routes.rb
- db/migrate/005_create_orders.rb
- db/schema.rb
- spec/factories/orders.rb
- spec/features/authenticated/user_can_view_their_past_orders_spec.rb
- spec/models/order_spec.rb
- spec/models/user_spec.rb
Added table for orders with foreign key to users
Migrated
Feature tests for authenticated user having orders
Authenticated user does not see another user's orders
Model tests for orders and users updated for relationship validation
@katiekeel @emcooper @JoelLindow
> Mhd story 12 past orders

- app/assets/stylesheets/application.css.scss
- app/models/item_order.rb
- app/views/orders/show.html.erb
- spec/features/authenticated/user_views_individual_order_spec.rb
- spec/models/item_order_spec.rb
- spec/models/order_spec.rb
- pulls subtotal logic out of Order show view, into model
- model tests for .subtotal and .total_price methods
- adds if statement to Order show page so that user can only see updated_at if status is cancelled or completed, per the user story
- styles order show page
@katiekeel @mdevoe12 @JoelLindow
> Story 13 Refactoring - closes #45

- app/controllers/orders_controller.rb
- app/views/items/_items.html.erb
- app/views/orders/show.html.erb
- config/routes.rb
- spec/features/authenticated/user_cannot_see_other_user_data_spec.rb
- spec/features/authenticated/user_views_individual_order_spec.rb
- spec/features/unauthenticated/user_cannot_see_registered_user_data_spec.rb
- spec/features/user_sees_retired_item_spec.rb
Authentication checks added for when user changes /orders/:id url, or when user is not logged in and tries to visit /orders. 
Also in this PR: test crash fixes from my previous PR, and an update to story 14 functionality after the Slack discussion with Mike.
What do you guys think of the index route in OrdersController? I could push it down to another method like Ellen did for the show view.
> Story 16/17

- app/controllers/orders_controller.rb
- app/models/item_order.rb
- app/models/order.rb
- app/views/carts/index.html.erb
- config/routes.rb
- db/migrate/009_add_default_to_orders_status.rb
- db/schema.rb
- spec/features/authenticated/user_can_checkout_spec.rb
- spec/features/authenticated/user_views_individual_order_spec.rb
Story 15 built out:
-Added order creation functionality
-Checkout functionality
-Checkout only displays if logged in and items are in the cart
> Mhd story 15 checkout

- app/controllers/carts_controller.rb
- spec/features/unauthenticated/user_decreases_cart_quantity_spec.rb
Changed the update cart functionality so that when you change quantity to 0 item is removed from cart,
> Cart Quantity 0

- app/controllers/carts_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/controllers/welcome_controller.rb
Minor controller updates, creating private methods for repeated logic.
> Dry up controllers

- app/assets/stylesheets/application.css.scss
- app/controllers/users_controller.rb
- app/models/order.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/orders/show.html.erb
- app/views/sessions/new.html.erb
- app/views/users/_form.html.erb
- app/views/users/edit.html.erb
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- spec/factories/traits.rb
- spec/features/authenticated/user_can_checkout_spec.rb
- spec/features/authenticated/user_cannot_see_other_user_data_spec.rb
- spec/features/authenticated/user_logs_in_to_site_spec.rb
- spec/features/authenticated/user_visits_dashboard_spec.rb
- spec/features/unauthenticated/user_can_create_new_account_spec.rb
- spec/features/unauthenticated/user_cannot_see_registered_user_data_spec.rb
- spec/features/user_can_log_out_spec.rb
User can now see dashboard with tab setup of profile information, edit account, view past orders, view most ordered item, and delete account.
Had to add some dependent: :destroys in models to make sure that when user deletes account nothing errors out. Also, cleared session/cookie in user controller to prevent similar errors.
> User dashboard

- app/controllers/orders_controller.rb
- app/models/cart.rb
- spec/features/authenticated/user_can_checkout_spec.rb
- temp.txt
Updated feature test to ensure cart clears after checkout
Added "empty_cart" method in cart class to clear contents
@emcooper @JoelLindow @katiekeel
> added test to make sure cart clears

- app/assets/stylesheets/application.css.scss
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/views/carts/index.html.erb
- app/views/layouts/application.html.erb
- app/views/sessions/new.html.erb
- app/views/users/_form.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- spec/features/authenticated/user_logs_in_to_site_spec.rb
- spec/features/unauthenticated/user_can_create_new_account_spec.rb
- spec/features/user_can_log_out_spec.rb
- updates tests for reflect new button and link text that Katie added
- changed logout route to DELETE from GET (to be RESTful) - I clicked around and logged out from a bunch of pages and it seemed to be fine - let me know if you find any issues in the future
- changed update cart quantity to PATCH (to be RESTful)
- cleared flash notice upon successful login (it lingered if you were unsuccessful at first)
- minor styling 
- noticed that a not logged in user that tries to go to '/dashboard' has an error thrown so I added a redirect to the login page
> Test Fixes and Refactoring - closes #49

- app/controllers/users_controller.rb
- app/views/admin/admin/index.html.erb
- spec/features/admin/admin_cannot_modify_users_spec.rb
Admin can: Log in
Admin can not: Edit other users information
Admin can not: View standard user dashboard
Admin can: Do what admin want!
> Branch: 20_admin_edits

- app/assets/stylesheets/application.css.scss
- app/controllers/admin/admin_controller.rb
- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/admin/admin/index.html.erb
- config/routes.rb
- spec/features/admin/admin_can_see_all_orders_spec.rb
Story 21 implemented.
Admin can see all orders, change order status, and view individual orders
> 21 admin orders

- app/controllers/application_controller.rb
- app/views/orders/show.html.erb
- db/migrate/010_add_fullname_and_address_to_user.rb
- db/schema.rb
- spec/features/admin/admin_can_see_individual_order_spec.rb
Story 23 Completed
Admin can see individual order information
Feature tests pass
@emcooper @JoelLindow @katiekeel
> Mhd story 22 admin views order

- app/controllers/admin/items_controller.rb
- app/views/admin/items/_form.html.erb
- app/views/admin/items/edit.html.erb
- spec/features/admin/admin_can_create_item_spec.rb
- spec/features/admin/admin_edits_an_item_spec.rb
> Story 25 aww yeah

- spec/features/admin/admin_can_see_dashboard_spec.rb
- spec/features/admin/admin_cannot_modify_users_spec.rb
- spec/features/admin/admin_edits_an_item_spec.rb
-Added sad path testing for Admin Edits Items (no title, default picture provided)
-Removed commented out lines from tests (user stories)
-Added test for admin visiting dashboard from root_path
@emcooper @JoelLindow @katiekeel
> Additional Sad Path Testing

- app/models/cart.rb
- spec/models/cart_spec.rb
Also minor refactor for total_price, just thought it looked better without the .sum but don't feel strongly about it.
> Model Tests for Cart - closes #58

- app/assets/stylesheets/application.css.scss
- app/views/admin/admin/index.html.erb
- app/views/layouts/application.html.erb
- app/views/welcome/index.html.erb
- db/seeds.rb
images added to carousel. need to be cropped wth css and moved up 40 pixels or so to frame correctly
> SEE NOTES!

- app/views/carts/index.html.erb
- app/views/categories/show.html.erb
- app/views/items/_item.html.erb
- app/views/items/_items.html.erb
- spec/features/authenticated/user_can_checkout_spec.rb
- spec/features/authenticated/users_cart_persists_upon_logout_spec.rb
- spec/features/unauthenticated/user_adds_item_to_cart_spec.rb
- spec/features/unauthenticated/user_can_increase_cart_quantity_of_item_spec.rb
- spec/features/unauthenticated/user_decreases_cart_quantity_spec.rb
- spec/features/unauthenticated/user_deletes_item_from_cart_spec.rb
- spec/features/unauthenticated/user_visits_category_show_spec.rb
- spec/features/unauthenticated/user_visits_items_index_spec.rb
- spec/features/unauthenticated_user_can_login_and_see_cart_spec.rb
Created Modal Views for Item Show in
Items Index
Categories
Cart
Updated existing tests for modal views.
> Mhd modal implementation

- app/views/welcome/index.html.erb
simple paragraph added
*no delivery to mordor available
> 'about' updated

- app/models/item.rb
- app/models/order.rb
- app/views/admin/admin/index.html.erb
- spec/models/item_spec.rb
- spec/models/order_spec.rb
- adds item validations per story #23 
- refactors the filtering by status for orders into one method
> Item validations & minor refactoring - closes #108

- app/models/user.rb
- app/views/users/show.html.erb
- spec/features/admin/admin_can_logs_in_spec.rb
- spec/features/admin/admin_can_see_all_orders_spec.rb
- spec/features/admin/admin_can_see_individual_order_spec.rb
- spec/features/admin/admin_edits_an_item_spec.rb
- spec/models/user_spec.rb
Got most ordered item working, not pretty but it works...
Also removed the comments from some of the tests.
> Most ordered item & Removes Test Comments
